services:
  - type: web
    name: saturn-backend
    env: docker
    plan: free
    region: oregon
    dockerfilePath: ./Dockerfile
    buildCommand: ""
    startCommand: ""
    envVars:
      - key: DJANGO_SECRET_KEY
        value: your-secret-key
      - key: DEBUG
        value: false
      - key: DJANGO_SETTINGS_MODULE
        value: saturn_dw.settings.local
