# Generated by Django 4.2.23 on 2025-06-18 05:21

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schemas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StructuredRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('record_id', models.UUIDField(help_text='Logical group for record versions')),
                ('data', models.JSONField(help_text='Actual structured record (validated)')),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_latest', models.BooleanField(default=True)),
                ('valid_from', models.DateTimeField(auto_now_add=True)),
                ('valid_to', models.DateTimeField(blank=True, null=True)),
                ('schema', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='structured_records', to='schemas.schemadefinition')),
            ],
            options={
                'ordering': ['-valid_from'],
                'unique_together': {('record_id', 'version')},
            },
        ),
    ]
