# Generated by Django 4.2.23 on 2025-06-18 05:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UnstructuredDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('doc_id', models.UUIDField(help_text='Groups versions of the same document')),
                ('content', models.JSONField()),
                ('text', models.TextField(help_text='Flattened content for search')),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_latest', models.BooleanField(default=True)),
                ('valid_from', models.DateTimeField(auto_now_add=True)),
                ('valid_to', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-valid_from'],
                'indexes': [models.Index(fields=['is_latest'], name='unstructure_is_late_e6f1e3_idx'), models.Index(fields=['text'], name='text_search_idx')],
                'unique_together': {('doc_id', 'version')},
            },
        ),
    ]
